sudo: required
services:
  - docker

language: go

go:
  - "1.12.x"

branches:
  only:
  - master

# This moves Kubernetes specific config files.
env:
- CHANGE_MINIKUBE_NONE_USER=true GO111MODULE=on

cache:
  directories:
  - .go/pkg/mod/

script:
- make docs
- make go-mod-download
- make build
- make start-kind
- make test

after_script:
- make stop-kind

