sudo: required

services:
- docker

# Selecting C as the language keeps the container to a minimum footprint. All
# go-specifc code is run in build container.
language: c

branches:
  only:
  - master

cache:
  directories:
  - .go/pkg/mod/cache
  - .go/cache

jobs:
  include:
    - stage: test
      script:
      - make docs
    - stage: test
      before_script:
      - make start-kind
      script:
      - make go-mod-download
      - make build
      - make test
      after_script:
      - make stop-kind

